/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Npc.Cleaner;
import Npc.Employee;
import Npc.Janitor;
import java.io.IOException;


/**
 *
 * @author Felhasznalo
 */
public class EmployeeMenu extends javax.swing.JPanel {
    GameFrame frame;
    public static int janitors;
    public static int cleaners;
    String employeeString;
    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu(GameFrame frame, String employeeString) {
        initComponents();
        this.employeeString = employeeString;
        this.frame = frame;
        int posX = frame.getLayeredPane().getMousePosition().x+20;
        int posY = frame.getLayeredPane().getMousePosition().y+7;
        setBounds(posX, posY, 179, 221);
        
        setFocusable(true);
        requestFocusInWindow(); 
        
        nameLabel.setText(employeeString.substring(0,1).toUpperCase() + employeeString.substring(1));
        jLabel1.setText("Employed " + employeeString + ":");
        jLabel4.setText("Wage of all " + employeeString + ":");
        jLabel6.setText("Wage of one " + employeeString.substring(0,employeeString.length()-1) + ":");
        janitors = frame.getGameEngine().getJanitors().size();
        cleaners = frame.getGameEngine().getCleaners().size();


        setLabels();
        
        
        
        
    }
    
    public void setLabels(){
        
        if(employeeString.equals("janitors")){
            janitors = frame.getGameEngine().getJanitors().size();
            numberLabel.setText(Integer.toString(janitors));
            oneWageLabel.setText("$2");
            allWageLabel.setText("$"+janitors*2);
        }else{
            cleaners = frame.getGameEngine().getCleaners().size();
            numberLabel.setText(Integer.toString(cleaners));
            oneWageLabel.setText("$1");
            allWageLabel.setText("$"+cleaners*1);
        }
    }

    public void addJanitor() throws IOException{
        if(janitors < 10){
            frame.getGameEngine().getJanitors().add(new Janitor(frame.getGameEngine().getMap(),frame.getGameEngine().getPlayer()));
            setLabels();
        }
    }
    
    public void removeJanitor() {
        if(janitors > 0 && frame.getGameEngine().getPlayer().getMoney() > 500){
            frame.getGameEngine().getJanitors().remove(0);
            frame.getGameEngine().getPlayer().setMoney(frame.getGameEngine().getPlayer().getMoney()-500);
            setLabels();
            frame.refreshMoneyLabel();
        }
    }
    
    public void addCleaner() throws IOException{
        if(cleaners < 10){
            frame.getGameEngine().getCleaners().add(new Cleaner(frame.getGameEngine().getMap(),frame.getGameEngine().getPlayer()));
            setLabels();
        }
    }
    
    public void removeCleaner() {
        if(cleaners > 0 && frame.getGameEngine().getPlayer().getMoney() > 300){
            frame.getGameEngine().getCleaners().remove(0);
            frame.getGameEngine().getPlayer().setMoney(frame.getGameEngine().getPlayer().getMoney()-300);
            setLabels();
            frame.refreshMoneyLabel();

        }
    }
    
    public void removeFromFrame(){
       frame.getLayeredPane().remove(this);
       frame.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        allWageLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oneWageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("___");
        nameLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employed ___:");

        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText("6");
        numberLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        allWageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allWageLabel.setText("$30");
        allWageLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Wage of all ___:");

        oneWageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneWageLabel.setText("$5");
        oneWageLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Wage of one ___:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allWageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oneWageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allWageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneWageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allWageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel oneWageLabel;
    // End of variables declaration//GEN-END:variables

    
}
