/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicScrollBarUI;

/**
 *
 * @author Felhasznalo
 */
public class HUD extends javax.swing.JPanel {
    GameFrame frame;
    int WIDTH;
    boolean started;
    int panelPosY;
    int panelHeight;
    int dragStartY;
    boolean isMoving;
    int posX;
    EmployeeMenu employeeMenu;
    /**
     * Creates new form HUD2
     */
    public HUD(GameFrame frame, int HEIGHT) {
        initComponents();
        this.frame = frame;
        WIDTH = 200;
        
        System.out.println(frame.getBounds().getSize());
        
        setBounds(0,0,WIDTH,HEIGHT);
        setSize(200,HEIGHT);
        started = frame.getGameSpeed().isRunning();
//        started = frame.getGameSpeed().isRunning();
        panelPosY = jPanel2.getBounds().y;
        panelHeight = jPanel2.getBounds().height;
        jPanel1.setSize(WIDTH,HEIGHT);
        isMoving = false;
        posX = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addCleanerLabel = new javax.swing.JLabel();
        removeCleanerLabel = new javax.swing.JLabel();
        cleanerLabel = new javax.swing.JLabel();
        addJanitorLabel = new javax.swing.JLabel();
        removeJanitorLabel = new javax.swing.JLabel();
        janitorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GFX/out.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(10, 0, 32, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(56, 10, 130, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel1MouseWheelMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 0, 10, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel2MouseWheelMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RollerCoaster");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("SlowCoaster");
        jLabel34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SmolCoaster");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("KidsCoaster");
        jLabel35.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DropTower");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("GoCart");
        jLabel36.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Dodgem");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Carousel");
        jLabel37.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("FerisWheel");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("DuckHunt");
        jLabel38.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("SlidePark");
        jLabel39.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PirateShip");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Toilet");
        jLabel40.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("HauntedCastle");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("LargeBush");
        jLabel41.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BallPit");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Buffet");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Restaurant");
        jLabel42.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Flowers");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("SimpleRoad");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("BigRock");
        jLabel43.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("FancyRoad");
        jLabel44.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("NiceTree");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Trashcan");
        jLabel45.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SmallBush");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("FunnyStatue");
        jLabel46.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CovidamPark™ (:");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 193, 950);

        add(jPanel1);
        jPanel1.setBounds(0, 250, 200, 930);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton5.setText("I I");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(30, 10, 40, 30);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton2.setText(">");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(80, 10, 40, 30);

        jButton1.setText(">>");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(130, 10, 40, 30);

        add(jPanel3);
        jPanel3.setBounds(0, 100, 200, 50);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Money:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 10, 80, 30);

        moneyLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        moneyLabel.setText("$10000");
        moneyLabel.setName("moneyLabel"); // NOI18N
        jPanel4.add(moneyLabel);
        moneyLabel.setBounds(102, 10, 90, 30);

        add(jPanel4);
        jPanel4.setBounds(0, 50, 200, 50);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        addCleanerLabel.setBackground(new java.awt.Color(153, 255, 153));
        addCleanerLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addCleanerLabel.setForeground(new java.awt.Color(0, 153, 51));
        addCleanerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCleanerLabel.setText("+");
        addCleanerLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 3, 2, new java.awt.Color(0, 0, 0)));
        addCleanerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCleanerLabel.setOpaque(true);
        addCleanerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addCleanerLabelMouseMoved(evt);
            }
        });
        addCleanerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCleanerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCleanerLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCleanerLabelMousePressed(evt);
            }
        });
        jPanel5.add(addCleanerLabel);
        addCleanerLabel.setBounds(110, 70, 40, 20);

        removeCleanerLabel.setBackground(new java.awt.Color(153, 0, 0));
        removeCleanerLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        removeCleanerLabel.setForeground(new java.awt.Color(255, 255, 255));
        removeCleanerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeCleanerLabel.setText("-");
        removeCleanerLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 3, 3, new java.awt.Color(0, 0, 0)));
        removeCleanerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeCleanerLabel.setOpaque(true);
        removeCleanerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                removeCleanerLabelMouseMoved(evt);
            }
        });
        removeCleanerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeCleanerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeCleanerLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeCleanerLabelMousePressed(evt);
            }
        });
        jPanel5.add(removeCleanerLabel);
        removeCleanerLabel.setBounds(150, 70, 40, 20);

        cleanerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GFX/cleaner.png"))); // NOI18N
        cleanerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cleanerLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        cleanerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cleanerLabelMouseMoved(evt);
            }
        });
        cleanerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cleanerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cleanerLabelMouseExited(evt);
            }
        });
        jPanel5.add(cleanerLabel);
        cleanerLabel.setBounds(110, 10, 80, 80);

        addJanitorLabel.setBackground(new java.awt.Color(153, 255, 153));
        addJanitorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addJanitorLabel.setForeground(new java.awt.Color(0, 153, 51));
        addJanitorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addJanitorLabel.setText("+");
        addJanitorLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 3, 2, new java.awt.Color(0, 0, 0)));
        addJanitorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addJanitorLabel.setOpaque(true);
        addJanitorLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addJanitorLabelMouseMoved(evt);
            }
        });
        addJanitorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addJanitorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addJanitorLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addJanitorLabelMousePressed(evt);
            }
        });
        jPanel5.add(addJanitorLabel);
        addJanitorLabel.setBounds(10, 70, 40, 20);

        removeJanitorLabel.setBackground(new java.awt.Color(153, 0, 0));
        removeJanitorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        removeJanitorLabel.setForeground(new java.awt.Color(255, 255, 255));
        removeJanitorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeJanitorLabel.setText("-");
        removeJanitorLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 3, 3, new java.awt.Color(0, 0, 0)));
        removeJanitorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeJanitorLabel.setOpaque(true);
        removeJanitorLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                removeJanitorLabelMouseMoved(evt);
            }
        });
        removeJanitorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeJanitorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeJanitorLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeJanitorLabelMousePressed(evt);
            }
        });
        jPanel5.add(removeJanitorLabel);
        removeJanitorLabel.setBounds(50, 70, 40, 20);

        janitorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GFX/maintenance.png"))); // NOI18N
        janitorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        janitorLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        janitorLabel.setOpaque(true);
        janitorLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                janitorLabelMouseMoved(evt);
            }
        });
        janitorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                janitorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                janitorLabelMouseExited(evt);
            }
        });
        jPanel5.add(janitorLabel);
        janitorLabel.setBounds(10, 10, 80, 80);

        add(jPanel5);
        jPanel5.setBounds(0, 150, 200, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frame.getGameSpeed().stop();
        started = false;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(started){
            frame.getGameSpeed().setDelay(1000);
        }else{
            frame.getGameSpeed().start();
            started = true;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(started){
            frame.getGameSpeed().setDelay(frame.getGameSpeed().getDelay()/2);
        }else{
            frame.getGameSpeed().start();
            started = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        closeHUD();
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        frame.getGameSpeed().stop();
        ExitMenu exitMenu = new ExitMenu(frame,frame.getGameSpeed(),frame.getGameMusic());
        frame.getLayeredPane().add(exitMenu,5,0);
        frame.getLayeredPane().moveToFront(exitMenu);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
    }//GEN-LAST:event_formMouseReleased

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        
    }//GEN-LAST:event_formMouseWheelMoved

    private void jPanel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel2MouseWheelMoved
        wheelMoved(evt);
    }//GEN-LAST:event_jPanel2MouseWheelMoved

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        jPanel2.setLocation(0,panelPosY = panelPosY - (panelPosY%10));
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel1MouseWheelMoved
        wheelMoved(evt);
    }//GEN-LAST:event_jPanel1MouseWheelMoved

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        dragStartY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        mouseDragged(evt);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        int mouseX = evt.getPoint().x;
        int mouseY = evt.getPoint().y;
        if(!jPanel2.getComponentAt(mouseX,mouseY).equals(jPanel2))      // IF NOT THE PANEL IS CLICKED
        {
            JLabel component = (JLabel)jPanel2.getComponentAt(mouseX, mouseY);
            if(component instanceof JLabel && !(component.equals(moneyLabel) || component.equals(jButton5) || component.equals(jButton2) || component.equals(jButton1) )){
                JLabel label = (JLabel)jPanel2.getComponentAt(mouseX, mouseY);
                String text = label.getText();

                SelectMenu selectMenu = new SelectMenu(text,frame,evt);
                frame.getLayeredPane().add(selectMenu,5,0);
                selectMenu.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        System.out.println("View.HUD.jLabel5MouseDragged()");
        if(panelPosY - (evt.getY()-dragStartY) <= 0 && panelPosY - (evt.getY()-dragStartY) > -770){
            jPanel2.setLocation(0,panelPosY-= (evt.getY()-dragStartY));
            jLabel5.setLocation(jLabel5.getLocation().x,jLabel5.getLocation().y+(evt.getY()-dragStartY));

        }  
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        dragStartY = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        jPanel2.setLocation(0,panelPosY = panelPosY - (panelPosY%10));
        jLabel5.setLocation(jLabel5.getLocation().x,jLabel5.getLocation().y - (jLabel5.getLocation().y %10));
    }//GEN-LAST:event_jLabel5MouseReleased

    private void janitorLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janitorLabelMouseMoved
        moveEmployeeMenu();
    }//GEN-LAST:event_janitorLabelMouseMoved

    private void janitorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janitorLabelMouseEntered
        addJanitorMenu();
    }//GEN-LAST:event_janitorLabelMouseEntered

    private void janitorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janitorLabelMouseExited
        exitEmployeeMenu();
    }//GEN-LAST:event_janitorLabelMouseExited

    private void cleanerLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanerLabelMouseMoved
        moveEmployeeMenu();
    }//GEN-LAST:event_cleanerLabelMouseMoved

    private void cleanerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanerLabelMouseEntered
        addCleanerMenu();
    }//GEN-LAST:event_cleanerLabelMouseEntered

    private void cleanerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanerLabelMouseExited
        exitEmployeeMenu();
    }//GEN-LAST:event_cleanerLabelMouseExited

    private void addJanitorLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJanitorLabelMousePressed
        try {
            employeeMenu.addJanitor();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_addJanitorLabelMousePressed

    private void addJanitorMenu(){
        employeeMenu = new EmployeeMenu(frame,"janitors");
        frame.getLayeredPane().add(employeeMenu,5,0);
        employeeMenu.requestFocusInWindow();
    }
    
    private void addCleanerMenu(){
        employeeMenu = new EmployeeMenu(frame,"cleaners");
        frame.getLayeredPane().add(employeeMenu,5,0);
        employeeMenu.requestFocusInWindow();
    }
    
    private void moveEmployeeMenu(){
        int x = frame.getLayeredPane().getMousePosition().x+20;
        int y = frame.getLayeredPane().getMousePosition().y+7;
        
        employeeMenu.setLocation(x,y);
    }
    
    private void exitEmployeeMenu(){
        employeeMenu.removeFromFrame();
    }
    
    private void removeJanitorLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeJanitorLabelMousePressed
        employeeMenu.removeJanitor();
        employeeMenu.setLabels();
    }//GEN-LAST:event_removeJanitorLabelMousePressed

    private void addCleanerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCleanerLabelMousePressed
        try {
            employeeMenu.addCleaner();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_addCleanerLabelMousePressed

    private void removeCleanerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCleanerLabelMousePressed
        employeeMenu.removeCleaner();
        employeeMenu.setLabels();
    }//GEN-LAST:event_removeCleanerLabelMousePressed

    private void removeJanitorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeJanitorLabelMouseEntered
        addJanitorMenu();
        removeJanitorLabel.setFont(new Font("Dialog",Font.BOLD,12));
        removeJanitorLabel.setText("$500");
    }//GEN-LAST:event_removeJanitorLabelMouseEntered

    private void addJanitorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJanitorLabelMouseEntered
        addJanitorMenu();
    }//GEN-LAST:event_addJanitorLabelMouseEntered

    private void addJanitorLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJanitorLabelMouseMoved
        moveEmployeeMenu();
    }//GEN-LAST:event_addJanitorLabelMouseMoved

    private void removeJanitorLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeJanitorLabelMouseMoved
        moveEmployeeMenu();
    }//GEN-LAST:event_removeJanitorLabelMouseMoved

    private void addJanitorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJanitorLabelMouseExited
        exitEmployeeMenu();
    }//GEN-LAST:event_addJanitorLabelMouseExited

    private void removeJanitorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeJanitorLabelMouseExited
        exitEmployeeMenu();
        removeJanitorLabel.setFont(new Font("Dialog",Font.BOLD,18));
        removeJanitorLabel.setText("-");
    }//GEN-LAST:event_removeJanitorLabelMouseExited

    private void addCleanerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCleanerLabelMouseEntered
        addCleanerMenu();
    }//GEN-LAST:event_addCleanerLabelMouseEntered

    private void addCleanerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCleanerLabelMouseExited
        exitEmployeeMenu();
    }//GEN-LAST:event_addCleanerLabelMouseExited

    private void removeCleanerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCleanerLabelMouseEntered
        addCleanerMenu();
        removeCleanerLabel.setFont(new Font("Dialog",Font.BOLD,12));
        removeCleanerLabel.setText("$300");
    }//GEN-LAST:event_removeCleanerLabelMouseEntered

    private void removeCleanerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCleanerLabelMouseExited
        exitEmployeeMenu();
        removeCleanerLabel.setFont(new Font("Dialog",Font.BOLD,18));
        removeCleanerLabel.setText("-");
    }//GEN-LAST:event_removeCleanerLabelMouseExited

    private void addCleanerLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCleanerLabelMouseMoved
        moveEmployeeMenu();
    }//GEN-LAST:event_addCleanerLabelMouseMoved

    private void removeCleanerLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCleanerLabelMouseMoved
        moveEmployeeMenu();
    }//GEN-LAST:event_removeCleanerLabelMouseMoved

    public void wheelMoved(java.awt.event.MouseWheelEvent evt){
        if(evt.getWheelRotation()<0 && panelPosY<0){
            jPanel2.setLocation(0,panelPosY+= 10);
            jLabel5.setLocation(jLabel5.getLocation().x,jLabel5.getLocation().y-10);
        }
        if(evt.getWheelRotation()>0 && panelPosY>-770){
            jPanel2.setLocation(0,panelPosY-= 10);
            jLabel5.setLocation(jLabel5.getLocation().x,jLabel5.getLocation().y+10);
        }
    }
    
    public void mouseDragged(java.awt.event.MouseEvent evt){
        if(panelPosY + (evt.getY()-dragStartY) <= 0 && panelPosY + (evt.getY()-dragStartY) > -770){
            jPanel2.setLocation(0,panelPosY+= (evt.getY()-dragStartY));
            jLabel5.setLocation(jLabel5.getLocation().x,jLabel5.getLocation().y-(evt.getY()-dragStartY));

        }        
    }
    
    public JLabel getMoneyLabel(){
            return moneyLabel;
    }
    
    private boolean stillInPanel(Point2D p) {
        return (janitorLabel.contains((Point)p) || cleanerLabel.contains((Point)p));
    }
    
    public void closeHUD(){
        Thread thread = new Thread(){
            @Override
            public void run(){
                isMoving = true;
                for(int i = 0; i < 200; i++){
                    setBounds(posX--,0,200, frame.getHeight());
                    try{
                        Thread.sleep(1);                    
                    }catch(Exception e){

                    }
                }
                isMoving = false;
            }
        };        
        if(!isMoving) thread.start();
    }
    
    public void openHud(){
        Thread thread = new Thread(){
            @Override
            public void run(){
                isMoving = true;

                for(int i = 0; i < 200; i++){
                    setBounds(posX++,0,200, frame.getHeight());
                    try{
                        Thread.sleep(1);                    
                    }catch(Exception e){

                    }
                }
                isMoving = false;

//                setBounds(posX,posY-250,417, 123);
            }
        };
        if(!isMoving) thread.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCleanerLabel;
    private javax.swing.JLabel addJanitorLabel;
    private javax.swing.JLabel cleanerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel janitorLabel;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JLabel removeCleanerLabel;
    private javax.swing.JLabel removeJanitorLabel;
    // End of variables declaration//GEN-END:variables
}
