/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Felhasznalo
 */
public class InfoPanel extends javax.swing.JPanel {
    int posX;
    int posY;
    boolean closed;
    GameFrame frame;
    static int instances = 0;
    /**
     * Creates new form InfoPanel
     */
    public InfoPanel(GameFrame frame,String text, String url) {
        if(instances<1){
            initComponents();
            posX = frame.getScreenSize().width/2-200;
            posY = frame.getScreenSize().height+100;
            setBounds(posX,posY,417, 123);
            jLabel1.setText("<html>" + text + "</html>");
            jLabel2.setIcon(new ImageIcon(getClass().getResource(url)));
            closed = false;
            this.frame = frame;
            frame.getLayeredPane().add(this,8,0);

            openInfo();
            
            instances++;
        }
    }
    
    private void openInfo(){
        Thread thread = new Thread(){
            @Override
            public void run(){
                for(int i = 0; i < 250; i++){
                    setBounds(posX,posY--,417, 123);
                    try{
                        Thread.sleep(1);                    
                    }catch(Exception e){

                    }
                }

//                setBounds(posX,posY-250,417, 123);
                
                try{
                    Thread.sleep(3000);
                    if(!closed){
                        closeInfo();
                    }
                }catch(Exception e){
                    
                }
            }
        };        
        thread.start();
    }
    
    private void closeInfo(){
        Thread thread = new Thread(){
            @Override
            public void run(){
                for(int i = 0; i < 250; i++){
                    setBounds(posX,posY++,417, 123);
                    
                    try{
                        Thread.sleep(1);                    
                    }catch(Exception e){
                    }
                }
                removeFromFrame();
            }
        };        
        thread.start();
//        setBounds(posX,posY+=250,417, 123);
//        removeFromFrame();
        instances--;
    }
    
    private void removeFromFrame(){
        frame.getLayeredPane().remove(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("dying of age is dying of not dying");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1);
        jLabel1.setBounds(30, 10, 280, 100);

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel2);
        jLabel2.setBounds(320, 32, 60, 60);

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(393, 3, 20, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        closeInfo();
        closed = true;
    }//GEN-LAST:event_jLabel3MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
