/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import GameEngine.Coordinate;
import GameEngine.Field;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Felhasznalo
 */
public class SelectMenu extends javax.swing.JPanel {

    /**
     * Creates new form SelectMenu
     */
    GameFrame frame;
    String name;
    private Scanner scanner;
    private String buildingSpecs[];
    Image img;
    
    public SelectMenu(String name,GameFrame frame, java.awt.event.MouseEvent evt) {
        initComponents();
        this.frame = frame;
        int posY = frame.getLayeredPane().getMousePosition().y - (int)(((float)frame.getLayeredPane().getMousePosition().y/frame.getLayeredPane().getSize().height)*336);
        int posX = frame.getLayeredPane().getMousePosition().x - (int)(((float)frame.getLayeredPane().getMousePosition().x/400)*250);
        
        try {
            img = ImageIO.read(new File("src/GFX/" + name+".png"));
        } catch (IOException ex) {
            Logger.getLogger(SelectMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jLabel1.setIcon(new ImageIcon(img));

        setBounds(posX, posY, 250, 336);
        getInfo(name);
        setLabels();
        addMouseListener(new MouseAdapter(){
            @Override
            public void mouseExited(MouseEvent evt){
                if(!stillInPanel(evt.getPoint())){
                    removeFromFrame();
                }
            }
        });
        addKeyListener(new KeyAdapter(){
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode() == KeyEvent.VK_ESCAPE){
                    removeFromFrame();
                }
            }
        });
        
        
        
        setFocusable(true);
        requestFocusInWindow();
    }
    
    private void removeFromFrame(){
       frame.getLayeredPane().remove(this);
       frame.repaint();
    }
    
    private boolean stillInPanel(Point2D p) {
    return (this.contains((Point)p));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel1);
        jLabel1.setBounds(9, 27, 232, 90);

        jLabel2.setBackground(new java.awt.Color(94, 176, 84));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 184, 86));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUY");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(71, 286, 113, 41);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel3);
        jLabel3.setBounds(10, 130, 232, 22);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Price:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel4);
        jLabel4.setBounds(10, 160, 232, 22);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Funnes:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel5);
        jLabel5.setBounds(10, 190, 232, 22);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Size:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel6);
        jLabel6.setBounds(10, 220, 232, 22);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Durability:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel7);
        jLabel7.setBounds(10, 250, 232, 22);

        jLabel9.setBackground(new java.awt.Color(204, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        add(jLabel9);
        jLabel9.setBounds(229, 3, 18, 18);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        removeFromFrame();
    }//GEN-LAST:event_formFocusLost

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        removeFromFrame();        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        int x = frame.getLayeredPane().getMousePosition().x;
        int y = frame.getLayeredPane().getMousePosition().y;
        
        frame.getHud().closeHUD();
        frame.getGameEngine().selectBuildingType(name);
        frame.getGameEngine().getSelectedBuilding().setLocation(new Field(x - (x % 40),y - (y % 40)));
        removeFromFrame();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void getInfo(String name) {
        this.name = name;        
        

        boolean l = false;
        try{
            scanner = new Scanner(new File("src/GFX/buildingStats.txt"));
            while(scanner.hasNextLine() && !l){
                String line = scanner.nextLine();
                if(line.split("\t")[0].equals(name)){
                    l = true;
                    buildingSpecs = new String[line.split("\t").length];
                    for(int i = 0; i < line.split("\t").length; i++){
                        buildingSpecs[i] = line.split("\t")[i];
                    }
                }
            }            
        }catch (FileNotFoundException e) {
                e.printStackTrace();
        }
    }

    private void setLabels(){
        jLabel3.setText(jLabel3.getText() + " " + name);
        jLabel4.setText(jLabel4.getText() + " " + Integer.parseInt(buildingSpecs[1]));
        jLabel5.setText(jLabel5.getText() + " " + Integer.parseInt(buildingSpecs[3]));
        jLabel6.setText(jLabel6.getText() + " " + Integer.parseInt(buildingSpecs[4]) + "x" + Integer.parseInt(buildingSpecs[5]));
//        jLabel7.setText(jLabel7.getText() + " " + )
        if(buildingSpecs.length == 9){
            jLabel7.setText(jLabel7.getText() + " " + Integer.parseInt(buildingSpecs[6]) );
        }else{
            remove(jLabel7);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
